version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/apps/server
    command: pnpm dev

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - server
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app/apps/web
    command: pnpm dev
