/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardUserImport } from './routes/dashboard-user'
import { Route as IndexImport } from './routes/index'
import { Route as MainLayoutMainImport } from './routes/_mainLayout/_main'
import { Route as AuthLayoutAuthImport } from './routes/_authLayout/auth'
import { Route as MainLayoutMainPublishingImport } from './routes/_mainLayout/_main.publishing'
import { Route as MainLayoutMainDashboardImport } from './routes/_mainLayout/_main.dashboard'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardUserRoute = DashboardUserImport.update({
  id: '/dashboard-user',
  path: '/dashboard-user',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutMainRoute = MainLayoutMainImport.update({
  id: '/_mainLayout/_main',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutAuthRoute = AuthLayoutAuthImport.update({
  id: '/_authLayout/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const MainLayoutMainPublishingRoute = MainLayoutMainPublishingImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => MainLayoutMainRoute,
} as any)

const MainLayoutMainDashboardRoute = MainLayoutMainDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MainLayoutMainRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard-user': {
      id: '/dashboard-user'
      path: '/dashboard-user'
      fullPath: '/dashboard-user'
      preLoaderRoute: typeof DashboardUserImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout/auth': {
      id: '/_authLayout/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthLayoutAuthImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/_main': {
      id: '/_mainLayout/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutMainImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout/_main/dashboard': {
      id: '/_mainLayout/_main/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainLayoutMainDashboardImport
      parentRoute: typeof MainLayoutMainImport
    }
    '/_mainLayout/_main/publishing': {
      id: '/_mainLayout/_main/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof MainLayoutMainPublishingImport
      parentRoute: typeof MainLayoutMainImport
    }
  }
}

// Create and export the route tree

interface MainLayoutMainRouteChildren {
  MainLayoutMainDashboardRoute: typeof MainLayoutMainDashboardRoute
  MainLayoutMainPublishingRoute: typeof MainLayoutMainPublishingRoute
}

const MainLayoutMainRouteChildren: MainLayoutMainRouteChildren = {
  MainLayoutMainDashboardRoute: MainLayoutMainDashboardRoute,
  MainLayoutMainPublishingRoute: MainLayoutMainPublishingRoute,
}

const MainLayoutMainRouteWithChildren = MainLayoutMainRoute._addFileChildren(
  MainLayoutMainRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard-user': typeof DashboardUserRoute
  '/login': typeof LoginRoute
  '/auth': typeof AuthLayoutAuthRoute
  '': typeof MainLayoutMainRouteWithChildren
  '/dashboard': typeof MainLayoutMainDashboardRoute
  '/publishing': typeof MainLayoutMainPublishingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard-user': typeof DashboardUserRoute
  '/login': typeof LoginRoute
  '/auth': typeof AuthLayoutAuthRoute
  '': typeof MainLayoutMainRouteWithChildren
  '/dashboard': typeof MainLayoutMainDashboardRoute
  '/publishing': typeof MainLayoutMainPublishingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard-user': typeof DashboardUserRoute
  '/login': typeof LoginRoute
  '/_authLayout/auth': typeof AuthLayoutAuthRoute
  '/_mainLayout/_main': typeof MainLayoutMainRouteWithChildren
  '/_mainLayout/_main/dashboard': typeof MainLayoutMainDashboardRoute
  '/_mainLayout/_main/publishing': typeof MainLayoutMainPublishingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard-user'
    | '/login'
    | '/auth'
    | ''
    | '/dashboard'
    | '/publishing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard-user'
    | '/login'
    | '/auth'
    | ''
    | '/dashboard'
    | '/publishing'
  id:
    | '__root__'
    | '/'
    | '/dashboard-user'
    | '/login'
    | '/_authLayout/auth'
    | '/_mainLayout/_main'
    | '/_mainLayout/_main/dashboard'
    | '/_mainLayout/_main/publishing'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardUserRoute: typeof DashboardUserRoute
  LoginRoute: typeof LoginRoute
  AuthLayoutAuthRoute: typeof AuthLayoutAuthRoute
  MainLayoutMainRoute: typeof MainLayoutMainRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardUserRoute: DashboardUserRoute,
  LoginRoute: LoginRoute,
  AuthLayoutAuthRoute: AuthLayoutAuthRoute,
  MainLayoutMainRoute: MainLayoutMainRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard-user",
        "/login",
        "/_authLayout/auth",
        "/_mainLayout/_main"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard-user": {
      "filePath": "dashboard-user.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authLayout/auth": {
      "filePath": "_authLayout/auth.tsx"
    },
    "/_mainLayout/_main": {
      "filePath": "_mainLayout/_main.tsx",
      "children": [
        "/_mainLayout/_main/dashboard",
        "/_mainLayout/_main/publishing"
      ]
    },
    "/_mainLayout/_main/dashboard": {
      "filePath": "_mainLayout/_main.dashboard.tsx",
      "parent": "/_mainLayout/_main"
    },
    "/_mainLayout/_main/publishing": {
      "filePath": "_mainLayout/_main.publishing.tsx",
      "parent": "/_mainLayout/_main"
    }
  }
}
ROUTE_MANIFEST_END */
