/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as SomethingIndexImport } from './routes/something/index'
import { Route as PublishingIndexImport } from './routes/publishing/index'
import { Route as JewerlyIndexImport } from './routes/jewerly/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SomethingIndexRoute = SomethingIndexImport.update({
  id: '/something/',
  path: '/something/',
  getParentRoute: () => rootRoute,
} as any)

const PublishingIndexRoute = PublishingIndexImport.update({
  id: '/publishing/',
  path: '/publishing/',
  getParentRoute: () => rootRoute,
} as any)

const JewerlyIndexRoute = JewerlyIndexImport.update({
  id: '/jewerly/',
  path: '/jewerly/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/jewerly/': {
      id: '/jewerly/'
      path: '/jewerly'
      fullPath: '/jewerly'
      preLoaderRoute: typeof JewerlyIndexImport
      parentRoute: typeof rootRoute
    }
    '/publishing/': {
      id: '/publishing/'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof PublishingIndexImport
      parentRoute: typeof rootRoute
    }
    '/something/': {
      id: '/something/'
      path: '/something'
      fullPath: '/something'
      preLoaderRoute: typeof SomethingIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/jewerly': typeof JewerlyIndexRoute
  '/publishing': typeof PublishingIndexRoute
  '/something': typeof SomethingIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/jewerly': typeof JewerlyIndexRoute
  '/publishing': typeof PublishingIndexRoute
  '/something': typeof SomethingIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/jewerly/': typeof JewerlyIndexRoute
  '/publishing/': typeof PublishingIndexRoute
  '/something/': typeof SomethingIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/jewerly'
    | '/publishing'
    | '/something'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/login' | '/jewerly' | '/publishing' | '/something'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/jewerly/'
    | '/publishing/'
    | '/something/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  JewerlyIndexRoute: typeof JewerlyIndexRoute
  PublishingIndexRoute: typeof PublishingIndexRoute
  SomethingIndexRoute: typeof SomethingIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  JewerlyIndexRoute: JewerlyIndexRoute,
  PublishingIndexRoute: PublishingIndexRoute,
  SomethingIndexRoute: SomethingIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/login",
        "/jewerly/",
        "/publishing/",
        "/something/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/jewerly/": {
      "filePath": "jewerly/index.tsx"
    },
    "/publishing/": {
      "filePath": "publishing/index.tsx"
    },
    "/something/": {
      "filePath": "something/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
